#!/bin/bash

set -e

rm /etc/nginx/sites-enabled/default
cat <<EOF > "/etc/nginx/sites-enabled/lua"
server {
	listen 80 default_server;

	location /ping {
		content_by_lua 'ngx.say("PONG")';
	}
}
EOF

nginx -t
invoke-rc.d nginx restart
curl --silent --fail -o /dev/null -w "response_code: %{http_code}\n" http://127.0.0.1/ping
