.TH "naxsi-ui-intercept" "1" "" "" ""
.SH "NAME"
naxsi-ui-intercept \- Wrapper script to launch the interceptor daemon for the 
naxsi-ui tool
.SH "SYNOPSIS"
\fBnaxsi-ui-intercept\fR
.SH "DESCRIPTION"
.PP
\fBnaxsi-ui-intercept\fR is the interceptor part of naxsi-ui which monitors HTTP 
requests from naxsi.
.SH "SEE ALSO"
Website: <http://code.google.com/p/naxsi/>
.TP
.SH "AUTHORS"
\fBnaxsi\fR was written by Thibault Koechlin <thibault.koechlin@nbs-system.com>.

\fBnaxsi-ui-intercept\fR was written by Cyril Lavier <cyril.lavier@davromaniak.eu>.
.TP
This manual page was written by Cyril Lavier <cyril.lavier@davromaniak.eu> for 
the Debian project (but may be used by others).
