.TH "naxsi-ui-extract" "1" "" "" ""
.SH "NAME"
naxsi-ui-extract \- Wrapper script to launch the extractor daemon for the 
naxsi-ui tool
.SH "SYNOPSIS"
\fBnaxsi-ui-extract\fR
.SH "DESCRIPTION"
.PP
\fBnaxsi-ui-extract\fR is the extractor part of naxsi-ui which reads the 
database and prints reports about blocked requests.
.SH "SEE ALSO"
Website: <http://code.google.com/p/naxsi/>
.TP
.SH "AUTHORS"
\fBnaxsi\fR was written by Thibault Koechlin <thibault.koechlin@nbs-system.com>.

\fBnaxsi-ui-extract\fR was written by Cyril Lavier <cyril.lavier@davromaniak.eu>.
.TP
This manual page was written by Cyril Lavier <cyril.lavier@davromaniak.eu> for 
the Debian project (but may be used by others).
